services:
  backend:
    build:
      context: ./bloglist-backend
      dockerfile: Dockerfile
    image: express-server
    env_file:
      - ./bloglist-backend/.env
    ports:
      - "3003:3003"
    container_name: backend

  frontend:
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./bloglist-frontend/.env
    ports:
      - "80:80"

  nginx-proxy:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - backend
      - frontend