PUT http://localhost:3003/api/blogs/685130448bc337ae90649ed5
Content-Type: application/json

{
  "title": "Harry Potter",
  "author": "Joanne Rowling",
  "url": "https://de.wikipedia.org/wiki/Joanne_K._Rowling",
  "likes": 1
}